module.exports = [
    "don't worry. no one actually knows what they're doing."
  , "this is Hard Stuff, but you can do it!"
  , "getting started is hard, you did it, congratulations!"
  , "If you can see this message it means you got it working and that's something to celebrate! ['hip','hip']!"
  , "you are the best around."
  , "nothing is ever going to keep you down!"
  , "computers are super hard, but you can defeat them!"
  , "it's okay to need a break, everyone needs one!"
  , "you got this."
  , "whoah you're pretty good at this."
  , "all the cats in the land bow down to your cool computer skills."
  , "there's a brazillion different ways to solve every problem - you only need one."
  , "oh, cool! check out what you just learned there!"
  , "learning something is the first step towards being awesome at it."
  , "don't be afraid to ask questions!"
  , "rad beans! lets try another!"
  , "impressive..."
  , "this is amazing! keep with the good work"
  , "you've already defeated so many obstacles to get here—keep going! you can do it."
  , "even the most accomplished computer people in the universe all make it up as they go along! this is okay."
  , "is your code a parking ticket? because it looks _fine_."
  , "node is cool, and so are you. :sparkles:"
  , "wowowowowow you've got some kick-ass node skillz."
  , "I can't believe what I'm seeing, you're awesome."
  , "I'm pretty sure you're now fully qualified fantastic human."
  , "looks like you're pretty much awesome now."
  , "omg - I'm falling head over heels for your sweet skills."
  , "look how far you've come! you're awesome!!"
  , "the best way to learn is by doing, and you are doing it good!"
  , "¡Lo estás haciendo muy bien!"
  , "keep going! you can do it!"
  , "mistakes are how we learn. keep making them! you're doing awesome!"
  , "✧･ﾟ\: \*✧･ﾟ\:\* you are super cool! \*\:･ﾟ✧\*\:･ﾟ✧"
  , "\✲ﾟ｡\.\(✿╹◡╹\)ﾉ☆\.｡₀\:\*ﾟ\✲ﾟ\*\:₀｡wow i cant believe how awesome this is"
  , "\"No bird soars in a calm\" - Wilbur Wright"
  , "Ayyyyyyy! so much WoW! very aWesome!!!"
  , "you finished a hard problem and learned something new. doesn't it feel great?"
  , "\"Nothing is impossible, the word itself says \'I\'m possible!\'\" - Audrey Hepburn"
  , "Never leave house without your towel."
  , "If 42 doesn't answer your question, try a prime number."
  , "i'm pretty new to this."
  , "You've got 99 problems but node ain't one"
  , "Hakuna Matata!"
  , "Reboot your life, everyday"
  , "\"May the force be with you, Node\"-JavaScript"
  , "Alright!! Way to go!!"
  , “The expert at anything, was once a beginner.”
  , "les petit ruisseaux font les grandes rivieres" 
  , "It's never too late!"
  , "Who's awesome? YOU'RE AWESOME!!!"
  , "did you ever know that you're my hero? you're everything i would like to be."
  , "charge forward!"
  , "one more step. you're almost there!"
  , "what lovely code you have!"
  , "Meow, you're paw-some"
  , "You totally did the thing!"
];
