module.exports = [
    "don't worry. no one actually knows what they're doing."
  , "this is Hard Stuff, but you can do it!"
  , "getting started is hard, you did it, congratulations!"
  , "If you can see this message it means you got it working and that's something to celebrate! ['hip','hip']!"
  , "you are the best around."
  , "nothing is ever going to keep you down!"
  , "computers are super hard, but you can defeat them!"
  , "it's okay to need a break, everyone needs one!"
  , "you got this."
  , "whoah you're pretty good at this."
  , "all the cats in the land bow down to your cool computer skills."
  , "there's a brazillion different ways to solve every problem - you only need one."
  , "oh, cool! check out what you just learned there!"
  , "learning something is the first step towards being awesome at it."
  , "don't be afraid to ask questions!"
  , "this is amazing! keep with the good work"
  , "you've already defeated so many obstacles to get here—keep going! you can do it."
  , "even the most accomplished computer people in the universe all make it up as they go along! this is okay."
  , "is your code a parking ticket? because it looks _fine_."
  , "node is cool, and so are you. :sparkles:"
  , "wowowowowow you've got some kick-ass node skillz."
  , "I can't believe what I'm seeing, you're awesome."
  , "I'm pretty sure you're now fully qualified fantastic human."
  , "looks like you're pretty much awesome now."
  , "omg - I'm falling head over heels for your sweet skills."
];
